apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "app.fullname" . }}
  labels:
      {{- include "app.labels" . | nindent 4 }}
spec:
  provider:
    yandexcertificatemanager:
      auth:
        authorizedKeySecretRef:
          name: {{ include "app.secretYcAuth" . }}
          key: authorized-key

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
      {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "app.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "app.secretTlsCerts" . }}
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: {{ .Values.yc.certId }}
        property: chain
    - secretKey: tls.key
      remoteRef:
        key: {{ .Values.yc.certId }}
        property: privateKey