apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.secret.value }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.secretYcAuth" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  authorized-key: {{ .Values.yc.authorizedKey }}