replicaCount: 1

image:
  repository: ghcr.io/carlosray/fa_react-front/frontend
  pullPolicy: IfNotPresent
imagePullSecrets: [ ]

podAnnotations: { }
podSecurityContext: { }
securityContext: { }

service:
  type: ClusterIP
  port: 80

container:
  port: 80

ingress:
  enabled: true
  hosts:
    - host: fa.ipvz.space
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - fa.ipvz.space

yc:
  authorizedKey: <FILL>
  certId: fpqdoqijs939pqhbsaql

env:
  - name: REACT_APP_BACKEND_URI
    value: "https://fa.ipvz.space/api"

config:
  mountPath: /etc/config
  value:
    example: test

secret:
  mountPath: /etc/secret
  value:
    example: test

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

probe:
  readiness:
    path: /
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  liveness:
    path: /
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  startup:
    path: /
    failureThreshold: 30
    periodSeconds: 10
    successThreshold: 1

nodeSelector: { }
tolerations: [ ]
affinity: { }
