name: Frontend App CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'dev/*'
    paths:
      - 'public/**'
      - 'src/**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/frontend:${{ github.sha }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          
  change-helm-app-version:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      
      - name: Commit new helm appVersion
        env:
          APP_VERSION: ${{ github.sha }}
        run: |
          cd .helm
          sed -i "/^\([[:space:]]*appVersion: \).*/s//\1\"${APP_VERSION}\"/" Chart.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "Changed helm app version"
          git push
