name: Change helm appVersion

on:
  workflow_dispatch:

jobs:
  change-helm-app-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      
      - name: Commit new helm appVersion
        env:
          APP_VERSION: ${{ github.sha }}
        run: |
          cd .helm
          sed -i "/^\([[:space:]]*appVersion: \).*/s//\1\"${APP_VERSION}\"/" Chart.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "Changed helm app version"
          git push
